dashboard/dashboard/urls.py
from django.contrib import admin
from django.urls import path
from web.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio),
    path('Dashboard/', inicio),
    path('Configuracion/', configuracion),
    path('Telegram/', telegram),
    path('Detecciones/', detecciones),
    path('Detectores/', detectores),
    path('Ayuda/', ayuda),
    path('video/<int:id_cam>', video),
    path('CrearCamara/', crear_camara),
    path('EditarCamara/<int:id_cam>', editar_camara),
    path('deleteCam/<int:id_cam>', eliminar_camara),
    path('deleteDetection/<int:id_detection>', eliminar_deteccion),
    path('deleteDetector/<int:id_detector>', eliminar_detector),
    path('deleteUser/<int:id_user>', eliminar_usuario),
    path('deleteGroup/<int:id_group>', eliminar_grupo),
    path('CrearDetector/', crear_detector),
    path('CrearUsuario/', crear_usuario),
    path('CrearGrupo/', crear_grupo),
    path('Camara/<int:id_cam>', detalles_camara),
    path('Deteccion/<int:id_detection>', detalles_deteccion),

]

dashboard/web/models.py
from django.db import models
from django.dispatch import receiver
import os


# Create your models here.


### TELEGRAM

class Group(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self) -> str:
        return str(self.name)


class User(models.Model):
    name = models.CharField(max_length=100)
    chat_id = models.CharField(max_length=100, unique=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self) -> str:
        return str(self.name)


### DETECTOR
class Detector(models.Model):
    name = models.CharField(max_length=255, unique=True)
    model = models.FileField(upload_to='models')

    def __str__(self) -> str:
        return str(self.name)


class Detection(models.Model):
    cam =  models.CharField(max_length=100, null=True, blank=True)
    date = models.DateTimeField(null=False, blank=False)
    img = models.ImageField(upload_to='static/detections')
    items = models.CharField(max_length=100, null=True, blank=True)
    pred = models.CharField(max_length=100, null=True, blank=True)
    detector =  models.CharField(max_length=100, null=True, blank=True)

    def __str__(self) -> str:
        if self.cam != None:
            return str(self.cam.name) + ": " + str(self.date)
        else:
            return "NoCam: " + str(self.date)


### CÁMARAS

class Cam(models.Model):
    name = models.CharField(max_length=100, unique=True)
    detector = models.ForeignKey(Detector, on_delete=models.SET_NULL, null=True, blank=True)
    url = models.CharField(max_length=2048)
    groups = models.ManyToManyField(Group, blank=True)

    def __str__(self) -> str:
        return str(self.name)


### Función que elimina el archivo en caso de ser eliminado su objeto
@receiver(models.signals.post_delete, sender=Detector)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    try:
        if instance.model:
            if os.path.isfile(instance.model.path):
                os.remove(instance.model.path)
                print("Archivo " + str(instance.model.name) + " eliminado")
            else:
                print("Archivo " + str(instance.model.name) + " no existe")
    except:
        print("Archivo " + str(instance.model.name) + " no ha podido ser eliminado")


### Función que elimina el archivo en caso de ser eliminado su objeto
@receiver(models.signals.post_delete, sender=Detection)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    try:
        if instance.img:
            if os.path.isfile(instance.img.path):
                os.remove(instance.img.path)
                print("Archivo " + str(instance.img.path) + " eliminado")
            else:
                print("Archivo " + str(instance.img.path) + " no existe")
    except:
        print("Archivo " + str(instance.img.path) + " no ha podido ser eliminado")

dashboard/web/templates/ayuda.html
{% extends 'base.html' %}
{% load static %}

{% block tituloPagina %} Inicio {% endblock %}

{% block contenido %}
<main role="main">
    <div class="container">
        <h1 class="text-center" style="margin-top: 30px;">Ayuda</h1>
        <p>¡Hola! Bienvenido a <strong>LiveGuardian</strong>, una aplicación desarrollada por José Joaquín Virtudes Castro, alumno de la ETSII en la Universidad de Sevilla, como su Trabajo Fin de Grado.
        LiveGuardian es una aplicación de videovigilancia potenciada con el poder de la inteligencia artificial. Esta permite visualizar y detectar
    objetos sobre múltiples cámaras en tiempo real, además de enviar alertas a usuarios por Telegram y almacenar las mismas.</p>
    <h3>Manual de usuario</h3>
        <p>En esta página dispones de un manual de usuario, donde se explica el uso de la interfaz, el proceso de instalación y la puesta en marcha.</p>

        </p>
        <div id="pdf-container">
            <object id="pdf" data="{% static 'Anexos.pdf' %}"></object>
        </div>
          
    </div>
</main>
{% endblock %}

dashboard/web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{titulo}}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/d4bff68adb.js" crossorigin="anonymous"></script>
</head>
<header>
  <nav class="dashboardNav navbar navbar-expand-lg sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"><i class="fas fa-eye"></i> {{titulo}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/Dashboard"><i class="fa-solid fa-video"></i> Dashboard</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-brain"></i> Detectar
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/Detectores">Detectores</a></li>
              <li><a class="dropdown-item" href="/Detecciones">Detecciones</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/Telegram"><i class="fa-brands fa-telegram"></i> Telegram</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/Configuracion"><i class="fa-solid fa-gear"></i>  Configuración</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/Ayuda"><i class="fa-solid fa-circle-info"></i>  Ayuda</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
<body>
    {% block contenido %}
    {% endblock %}
</body>
</html>

dashboard/web/templates/camara.html
{% extends 'base.html' %}

{% block tituloPagina %} Inicio {% endblock %}

{% block contenido %}
<main role="main">
    <div style="margin-top: 30px;">
        <div class="card fullwidth-card w-100 position-relative">
            <img class="card-img-top img-fluid rounded-image-fw" alt="{{cam.name}}" src="/video/{{cam.id}}">
            <form action="/Camara/{{cam.id}}" method="post">
                {% csrf_token %}
                <div class="position-absolute btn-container p-2" style="top: 0; left: 0; background-color: rgba(0, 0, 0, 0.5); color: white; border-radius: 0px 0px 15px 0px;">
                    <h2 class="mb-1 ocultable text-center" style="font-size: 1.25rem;">{{cam.name}}</h2>
                    {% if cam.detector == None %}
                    <div class="mb-1 ocultable text-center"><h4 style="font-size: 0.9rem;"><i class="fa-solid fa-brain"></i> Sin detector</h4></div>
                    {% else %}
                    <div class="haveDetector mb-1 ocultable text-center"><h4 style="font-size: 0.9rem;"><i class="fa-solid fa-brain"></i> {{cam.detector.name}}</h4></div>
                    {% endif %}
                    {% if cam.groups.all %}
                    <div class="haveTelegram mb-2 ocultable text-center"><h4 style="font-size: 0.9rem;"><i class="fa-brands fa-telegram"></i> {{cam.groups.first}}</h4></div>
                    {% else %}
                    <div class="mb-2 ocultable text-center"><h4 style="font-size: 0.9rem;"><i class="fa-brands fa-telegram"></i> Sin grupo </h4></div>
                    {% endif %}
                    <div class="ocultable"><a href="/deleteCam/{{cam.id}}" class="btn btn-delete d-block mb-1" style="font-size: 0.9rem;"><i class="fa-solid fa-trash"></i> Eliminar cámara</a></div>
                    <div class="ocultable"><a href="/EditarCamara/{{cam.id}}" class="btn btn-config d-block mb-1 ocultable" style="font-size: 0.9rem;"><i class="fa-solid fa-gear"></i> Configurar cámara</a></div>
                    <div class="ocultable">
                        <a class="btn btn-snapshot d-block mb-1" style="font-size: 0.9rem;" onclick="this.closest('form').submit();">
                            <i class="fa-solid fa-camera"></i> Tomar instantánea
                        </a>
                    </div>
                    <div id="toggleOverlay" class="btn btn-show d-block" style="font-size: 0.9rem;"><i class="fa-solid fa-eye"></i> Ocultar</div>
                </div>
            </form>
        </div>
    </div>

    <script>
        const toggleOverlay = document.getElementById("toggleOverlay");
        const ocultables = document.querySelectorAll(".ocultable");

        toggleOverlay.addEventListener("click", function () {
            ocultables.forEach(function (ocultable) {
                if (ocultable.style.display === "none") {
                    ocultable.style.display = "";
                    toggleOverlay.innerHTML = '<i class="fa-solid fa-eye"></i> Ocultar';
                } else {
                    ocultable.style.display = "none";
                    toggleOverlay.innerHTML = '<i class="fa-solid fa-eye"></i> Mostrar';
                }
            });
        });
    </script>
</main>
{% endblock %}

dashboard/web/templates/card.html
<div class="col-md-4 card-column">
  <a href="/Camara/{{cam.id}}">
  <div class="card mb-4 custom-card">
      <img class="img-fluid card-img"  alt="{{cam.name}}"
       src="/video/{{cam.id}}"> 
        <div class="card-img-overlay">
          <h5 class="card-title card-title-overlay">{{cam.name}}</h5>
        </div>
  </div>
  </a>
  <div class="icon-container">
      {% if cam.detector == None %}
        <div><i class="fa-solid fa-brain"></i> Sin detector</div>
      {% else %}
        <div class="haveDetector"><i class="fa-solid fa-brain"></i> {{cam.detector.name}}</div>
      {% endif %}
      {% if cam.groups.all %} 
        <div class="haveTelegram"><i class="fa-brands fa-telegram"></i> {{cam.groups.first}} </div>
      {% else %}
        <div><i class="fa-brands fa-telegram"></i> Sin grupo </div>
      {% endif %}
      
      <a href="/deleteCam/{{cam.id}}" class="icon-link">
        <div><i class="fa-solid fa-trash icon-trash"></i> </div>
      </a>
      <a href="EditarCamara/{{cam.id}}"class="icon-link">
        <div><i class="fa-solid fa-gear icon-gear"></i></div>
      </a>
      
  </div>
</div>

dashboard/web/templates/configuracion.html
{% extends 'base.html' %}

{% block tituloPagina %} Inicio {% endblock %}

{% block contenido %}
<main role="main">
    <h1 class="text-center" style="margin-top: 30px; color: var(--principal);">Configuración</h1>
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group row">
                <label for="framesToDetector" class="col-sm-3 col-form-label">Intervalo de fotogramas</label>
                <div class="col-sm-9">
                    <input type="number" id="framesToDetector" class="form-control" name="framesToDetector" value="{{framesToDetector}}" required>
                    <small class="form-text text-muted">
                        Este intervalo indica cada cuantos fotogramas será uno introducido en el detector.
                    </small>
                </div>
            </div>
            <div class="form-group row">
                <label for="historySize" class="col-sm-3 col-form-label">Tamaño del historial</label>
                <div class="col-sm-9">
                    <input type="number" id="historySize" class="form-control" name="historySize" value="{{historySize}}" required>
                    <small class="form-text text-muted">
                        Número de fotogramas almacenados (un número mayor puede producir retraso en las detecciones)
                    </small>
                </div>
            </div>
            <div class="form-group row">
                <label for="historySizeToDetect" class="col-sm-3 col-form-label">Nº de fotogramas para detectar</label>
                <div class="col-sm-9">
                    <input type="number" id="historySizeToDetect" class="form-control" name="historySizeToDetect" value="{{historySizeToDetect}}" required>
                    <small class="form-text text-muted">
                        Número de fotogramas necesarios en el historia para producirse una detección.
                    </small>
                </div>
            </div>
            <div class="form-group row">
                <label for="token" class="col-sm-3 col-form-label">Token bot Telegram</label>
                <div class="col-sm-9">
                    <input type="text" id="token" class="form-control" name="token" value="{{token}}" required>
                    <small class="form-text text-muted">
                        Token del bot de Telegram utilizado en el sistema.
                    </small>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-12 text-right">
                    <input type="submit" value="Guardar" class="btn btn-custom">
                </div>
            </div>
        </form>
    </div>
</main>
{% endblock %}

dashboard/web/templates/dashboard.html
{% extends 'base.html' %}

{% block tituloPagina %} Inicio {% endblock %}

{% block contenido %}
<main role="main">
    <h1 class="text-center" style="margin-top: 30px;">Cámaras</h1>
    <div class="album py-5">
    <div class="container">
        <div class="d-flex flex-row-reverse bd-highlight mb-2"><a href="/CrearCamara/"><button type="button" class="btn btn-custom"><i class="fas fa-plus"></i> Crear cámara</button></a>
        </div>
        <div class="row">
    {% for cam in cameras %}
    {% include "card.html" %}
    {% empty %}
    <h4>No se ha cargado ninguna cámara todavía.</h4>
    {% endfor %}
                </div>
            </div>
        </div>
    </main>
{% endblock %}

dashboard/web/templates/detalle_deteccion.html
{% extends 'base.html' %}

{% block tituloPagina %} Inicio {% endblock %}

{% block contenido %}
<main role="main">
    <div class="container mt-4">
        <div class="row">
            <div class="col-sm-8">
                <img class="img-fluid" alt="{{detection.img.name}}" src="{{detection.img.url}}" style="border-radius: 5px;">
            </div>
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-header">
                        <h2 class="display-6">Detección #{{detection.id}}</h2>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <strong><i class="fa-solid fa-camera"></i> Cámara:</strong>
                            {% if detection.cam == None %}
                                <span>Desconocida</span>
                            {% else %}
                                <span>{{detection.cam}}</span>
                            {% endif %}
                        </li>
                        <li class="list-group-item">
                            <strong><i class="fa-solid fa-brain"></i> Detector:</strong>
                            {% if detection.detector == None %}
                                <span>Sin detector</span>
                            {% else %}
                                <span>{{detection.detector}}</span>
                            {% endif %}
                        </li>
                        <li class="list-group-item">
                            <strong><i class="fas fa-box"></i> Items:</strong>
                            {% if detection.items == None %}
                                <span>-</span>
                            {% else %}
                                <span>{{detection.items}}</span>
                            {% endif %}
                        </li>
                        <li class="list-group-item">
                            <strong><i class="fas fa-percentage"></i> Probabilidades:</strong>
                            {% if detection.pred == None %}
                                <span>-</span>
                            {% else %}
                                <span>{{detection.pred}}</span>
                            {% endif %}
                        </li>
                        <li class="list-group-item">
                            <strong><i class="fa-solid fa-calendar-days"></i> Fecha:</strong>
                            <span>{{detection.date}}</span>
                        </li>
                    </ul>
                    <div class="card-footer">
                        <a href="/deleteDetection/{{detection.id}}" class="icon-link">
                            <button type="button" class="btn btn-danger"><i class="fa-solid fa-trash"></i> Eliminar detección</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

dashboard/web/templates/detecciones.html
{% extends 'base.html' %}

{% block tituloPagina %} Inicio {% endblock %}

{% block contenido %}
<main role="main">
    <h1 class="text-center" style="margin-top: 30px;">Detecciones</h1>
    <div class="container">
        <table class="table">
            <thead>
              <tr>
                <th scope="col"><i class="far fa-eye"></i></th>
                <th scope="col"><i class="fa-solid fa-key"></i> Id</th>
                <th scope="col"><i class="fa-solid fa-camera"></i> Cámara</th>
                <th scope="col"><i class="fa-solid fa-calendar-days"></i> Fecha</th>
                <th scope="col"><i class="fa-solid fa-brain"></i> Detector</th>
              </tr>
            </thead>
            <tbody>
                {% for detection in detections %}
                <tr>
                    <th scope="row"><a href="/Deteccion/{{detection.id}}"> Ver </a></th>
                    <td>{{detection.id}}</td>
                    <td>{% if detection.cam == None %} Cámara desconocida {% else %}{{detection.cam}} {% endif %}</td>
                    <td>{{detection.date}}</td>
                    <td>{% if detection.detector == None %} Sin detector {% else %}{{detection.detector}} {% endif %}</td>
                  </tr>
                {% endfor %}

            </tbody>
          </table>
    </div>
    </main>
{% endblock %}

dashboard/web/templates/detectores.html
{% extends 'base.html' %}

{% block tituloPagina %} Inicio {% endblock %}

{% block contenido %}
<main role="main">
    <h1 class="text-center" style="margin-top: 30px;">Detectores</h1>
    <div class="container">
        <div class="d-flex flex-row-reverse bd-highlight"><a href="/CrearDetector/"><button type="button" class="btn btn-custom"><i class="fas fa-plus"></i> Crear detector</button></a></div>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Eliminar</th>
                <th scope="col"><i class="fa-solid fa-signature"></i> Nombre</th>
                <th scope="col"><i class="fa-solid fa-brain"></i> Modelo</th>
              </tr>
            </thead>
            <tbody>
                {% for detector in detectors %}
                <tr>
                    <th scope="row"><a href="/deleteDetector/{{detector.id}}" class="icon-link"> <i class="fa-solid fa-trash icon-trash"></i> </a></th>
                    <td>{{detector.name}}</td>
                    <td>{{detector.model}}</td>
                  </tr>
                {% endfor %}

            </tbody>
          </table>
    </div>
    </main>
{% endblock %}

dashboard/web/templates/formulario.html
{% extends 'base.html' %}

{% block tituloPagina %} Inicio {% endblock %}

{% block contenido %}
<main role="main">
    <div class="container">
        <h1 class="text-center mt-4" >{{titulo}}</h1>
        <form action="{{ruta}}" method="post" class="text-center" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{form}}
                <input type='submit' value='Crear' class="btn btn-custom" style="margin-top: 1rem;"/>
            </div>
        </form>
    </div>
</main>
{% endblock %}

dashboard/web/templates/telegram.html
{% extends 'base.html' %}

{% block tituloPagina %} Inicio {% endblock %}

{% block contenido %}
<main role="main">
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                <h1 class="text-center" style="margin-top: 30px;">Grupos</h1>
                <div class="d-flex flex-row-reverse bd-highlight"><a href="/CrearGrupo/"><button type="button" class="btn btn-custom"><i class="fas fa-plus"></i> Crear grupo</button></a></div>
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col"><i class="fa-solid fa-trash"></i></th>
                        <th scope="col"><i class="fa-solid fa-signature"></i> Nombre</th>
                        <th scope="col"><i class="fa-solid fa-person"></i> Nº usuarios</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for group in groups %}
                        <tr>
                            <th scope="row"><a href="/deleteGroup/{{group.id}}" class="icon-link"> <i class="fa-solid fa-trash icon-trash"></i> </a></th>
                            <td>{{group.name}}</td>
                            <td>{{group.user_set.all|length}}</td>
                          </tr>
                        {% endfor %}
                    </tbody>
                  </table>
            </div>
            <div class="col-sm-7">
                <h1 class="text-center" style="margin-top: 30px;">Usuarios</h1>
                <div class="d-flex flex-row-reverse bd-highlight"><a href="/CrearUsuario/"><button type="button" class="btn btn-custom"><i class="fas fa-plus"></i> Crear usuario</button></a></div>
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col"><i class="fa-solid fa-trash"></i></th>
                        <th scope="col"><i class="fa-solid fa-signature"></i> Nombre</th>
                        <th scope="col"><i class="fa-solid fa-id-card"></i> Chat Id</th>
                        <th scope="col"><i class="fa-solid fa-people-group"></i> Grupo</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                        <tr>
                            <th scope="row"><a href="/deleteUser/{{user.id}}" class="icon-link"> <i class="fa-solid fa-trash icon-trash"></i> </a></th>
                            <td>{{user.name}}</td>
                            <td>{{user.chat_id}}</td>
                            <td>{{user.group.name}}</td>
                          </tr>
                        {% endfor %}
                    </tbody>
                  </table>
            </div>
        </div>
    </div>
    </main>
{% endblock %}